# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: micronautservice
services:
  app:
    image: micronautservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - MICRONAUT_METRICS_ENABLED=true
      - DATASOURCE_URL=jdbc:postgresql://postgresql:5432/micronautservice
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
